"""Generate the frontend's wire schemas from the API's own response models.

Every route with a ``response_model`` already validates what it returns
against a pydantic model; this writes the same shapes as zod so the browser
validates what it receives (``Habibi/src/api/wire/generated.ts``). One
source of truth, two ends of the wire, no hand-written mirror to drift.

    python scripts/gen_wire_schemas.py            # writes the file
    python scripts/gen_wire_schemas.py --check    # exits 1 when it is stale

Only response shapes are emitted (what a 200 carries); request models are
typed by the API and refused there. Objects are ``.passthrough()`` so a key
the model does not name is kept, never stripped: the backend serialises
through the same model, so nothing extra arrives, and a parse failure means
the two ends disagree.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "Habibi" / "src" / "api" / "wire" / "generated.ts"
CONSTANTS_OUT = OUT.with_name("constants.json")
HEADER = """// GENERATED by backend/scripts/gen_wire_schemas.py from the API's response models.
// Do not edit; regenerate. backend/tests/test_wire_schemas_current.py fails when it is stale.
/* eslint-disable */
import { z } from "zod";

"""


def _ident(name: str) -> str:
    return re.sub(r"\W", "_", name)


class Gen:
    def __init__(self, components: dict) -> None:
        self.components = components
        self.emitted: dict[str, str] = {}
        self.order: list[str] = []
        self.in_progress: set[str] = set()
        self.lazy: set[str] = set()

    def ref_name(self, ref: str) -> str:
        return ref.rsplit("/", 1)[-1]

    def ensure(self, name: str) -> str:
        ident = _ident(name)
        if name in self.emitted:
            return ident
        if name in self.in_progress:
            self.lazy.add(name)
            return ident  # recursion: the reference is wrapped in z.lazy by the caller
        self.in_progress.add(name)
        body = self.expr(self.components[name], top=True)
        self.in_progress.discard(name)
        self.emitted[name] = body
        self.order.append(name)
        return ident

    def expr(self, s: dict, *, top: bool = False) -> str:
        if "$ref" in s:
            name = self.ref_name(s["$ref"])
            ident = self.ensure(name)
            if name in self.in_progress or name in self.lazy:
                return f"z.lazy(() => {ident})"
            return ident
        if "anyOf" in s or "oneOf" in s:
            options = s.get("anyOf") or s.get("oneOf")
            nullable = any(o.get("type") == "null" for o in options)
            rest = [o for o in options if o.get("type") != "null"]
            if not rest:
                return "z.null()"
            exprs = list(dict.fromkeys(self.expr(o) for o in rest))
            expr = exprs[0] if len(exprs) == 1 else "z.union([" + ", ".join(exprs) + "])"
            return f"{expr}.nullable()" if nullable else expr
        if "allOf" in s:
            parts = s["allOf"]
            if len(parts) == 1:
                return self.expr(parts[0])
            return " ".join([self.expr(parts[0])] + [f".and({self.expr(p)})" for p in parts[1:]])
        if "const" in s:
            return f"z.literal({json.dumps(s['const'])})"
        if "enum" in s:
            values = s["enum"]
            if all(isinstance(v, str) for v in values):
                return "z.enum([" + ", ".join(json.dumps(v) for v in values) + "])"
            return "z.union([" + ", ".join(f"z.literal({json.dumps(v)})" for v in values) + "])"
        t = s.get("type")
        if isinstance(t, list):
            nullable = "null" in t
            kinds = [k for k in t if k != "null"]
            expr = self.expr({**s, "type": kinds[0]}) if len(kinds) == 1 else "z.union([" + ", ".join(self.expr({**s, "type": k}) for k in kinds) + "])"
            return f"{expr}.nullable()" if nullable else expr
        if t == "string":
            return "z.string()"
        if t in ("integer", "number"):
            return "z.number()"
        if t == "boolean":
            return "z.boolean()"
        if t == "null":
            return "z.null()"
        if t == "array":
            items = s.get("items")
            return f"z.array({self.expr(items) if items else 'z.unknown()'})"
        if t == "object" or "properties" in s:
            props = s.get("properties") or {}
            if not props:
                extra = s.get("additionalProperties")
                if isinstance(extra, dict) and extra:
                    return f"z.record(z.string(), {self.expr(extra)})"
                return "z.record(z.string(), z.unknown())"
            required = set(s.get("required") or [])
            lines = []
            for key, sub in props.items():
                e = self.expr(sub)
                if key not in required:
                    e += ".optional()"
                lines.append(f"  {json.dumps(key)}: {e},")
            return "z.object({\n" + "\n".join(lines) + "\n}).passthrough()"
        return "z.unknown()"


def build() -> str:
    import main  # noqa: PLC0415

    spec = main.app.openapi()
    gen = Gen(spec["components"]["schemas"])
    routes: list[tuple[str, str, str]] = []
    for path, ops in spec["paths"].items():
        for method, op in ops.items():
            content = op.get("responses", {}).get("200", {}).get("content", {})
            schema = next((c.get("schema") for k, c in content.items() if k.startswith("application/json")), None)
            if schema is None:
                continue
            routes.append((method.upper(), path, gen.expr(schema)))
    out = [HEADER]
    for name in gen.order:
        ident = _ident(name)
        body = gen.emitted[name]
        if name in gen.lazy:
            out.append(f"export const {ident}: z.ZodTypeAny = {body};\n")
        else:
            out.append(f"export const {ident} = {body};\n")
    out.append("\n/** `METHOD /path/{param}` -> the schema of its 200 body, in the API's registration order. */\n")
    out.append("export const ROUTES: ReadonlyArray<readonly [string, z.ZodTypeAny]> = [\n")
    for method, path, expr in routes:
        out.append(f"  [{json.dumps(method + ' ' + path)}, {expr}],\n")
    out.append("];\n")
    return "".join(out)


def build_constants() -> str:
    """The values both ends of the wire agree on, from their Python owners.

    Each of these was a hand-mirrored literal in the TypeScript: the dispute
    SLA warning fraction, the rollback triggers, the promise, reminder and
    sender vocabularies. A vocabulary that grows on one side and not the
    other is a select with a missing option or a lozenge with no tone; the
    file is the mirror now and the test keeps it current.
    """
    from typing import get_args

    import db
    from agent_core.cards.schema import RollbackTrigger
    from schemas.common import PromiseStatus, ReminderStatus, Sender

    constants = {
        "_comment": "GENERATED by backend/scripts/gen_wire_schemas.py. Do not edit; regenerate.",
        "disputeSlaWarnFraction": db.DISPUTE_SLA_WARN_FRACTION,
        "rollbackTriggers": list(get_args(RollbackTrigger)),
        "promiseStatuses": list(get_args(PromiseStatus)),
        "reminderStatuses": list(get_args(ReminderStatus)),
        "senders": list(get_args(Sender)),
    }
    return json.dumps(constants, indent=2) + "\n"


def main_() -> int:
    text = build()
    constants = build_constants()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        current_constants = CONSTANTS_OUT.read_text(encoding="utf-8") if CONSTANTS_OUT.exists() else ""
        if current.replace("\r\n", "\n") != text or current_constants.replace("\r\n", "\n") != constants:
            print(f"{OUT} is stale: run python scripts/gen_wire_schemas.py", file=sys.stderr)
            return 1
        print("wire schemas are current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    CONSTANTS_OUT.write_text(constants, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({text.count(chr(10))} lines) and {CONSTANTS_OUT.name}")
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    raise SystemExit(main_())
