"""Write THIRD_PARTY_NOTICES.txt at the repo root: every pinned backend
distribution and every direct console dependency, with the licence each
declares.

    python scripts/third_party_notices.py            # rewrite the file
    python scripts/third_party_notices.py --check    # exit 1 if it is stale

Backend rows come from requirements.lock (names and versions) and the licence
from the installed distribution's metadata when it is installed here, else
"(not installed here)". Console rows come from Habibi/package.json's
dependencies and the licence from node_modules/<name>/package.json. Nothing
is fetched; the file is what the lockfiles and the installed trees say.
"""

from __future__ import annotations

import json
import re
import sys
from importlib import metadata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BACKEND = ROOT / "backend"
HABIBI = ROOT / "Habibi"
OUT = ROOT / "THIRD_PARTY_NOTICES.txt"


def _license_of(dist: metadata.Distribution) -> str:
    meta = dist.metadata
    expr = meta.get("License-Expression")
    if expr:
        return str(expr)
    lic = (meta.get("License") or "").strip()
    if lic and "\n" not in lic and len(lic) < 60:
        return lic
    for c in meta.get_all("Classifier") or []:
        if c.startswith("License ::"):
            return c.split("::")[-1].strip()
    return lic.splitlines()[0][:60] if lic else "(unstated)"


def backend_rows() -> list[tuple[str, str, str]]:
    rows = []
    for line in (BACKEND / "requirements.lock").read_text(encoding="utf-8").splitlines():
        m = re.match(r"^([A-Za-z0-9_.\-]+)(?:\[[^\]]*\])?==([^ \\]+)", line)
        if not m:
            continue
        name, version = m.group(1), m.group(2)
        try:
            lic = _license_of(metadata.distribution(name))
        except metadata.PackageNotFoundError:
            lic = "(not installed here)"
        rows.append((name, version, lic))
    return sorted(rows, key=lambda r: r[0].lower())


def console_rows() -> list[tuple[str, str, str]]:
    pkg = json.loads((HABIBI / "package.json").read_text(encoding="utf-8"))
    rows = []
    for name, spec in sorted(pkg.get("dependencies", {}).items()):
        installed = HABIBI / "node_modules" / name / "package.json"
        if installed.exists():
            meta = json.loads(installed.read_text(encoding="utf-8"))
            version = str(meta.get("version") or spec)
            lic = meta.get("license")
            if isinstance(lic, dict):
                lic = lic.get("type")
            lic = str(lic or "(unstated)")
        else:
            version, lic = spec, "(not installed here)"
        rows.append((name, version, lic))
    return rows


def render() -> str:
    lines = [
        "THIRD-PARTY NOTICES",
        "",
        "This product is proprietary (see LICENSE). It is built on the open-source",
        "components below, each used under its own licence. Generated by",
        "backend/scripts/third_party_notices.py from the lockfiles; do not edit by hand.",
        "",
        "Backend (requirements.lock)",
        "",
    ]
    for name, version, lic in backend_rows():
        lines.append(f"  {name} {version} -- {lic}")
    lines += ["", "Console (Habibi/package.json dependencies)", ""]
    for name, version, lic in console_rows():
        lines.append(f"  {name} {version} -- {lic}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.exists() else ""
        if current != text:
            sys.stderr.write("THIRD_PARTY_NOTICES.txt is stale: run python scripts/third_party_notices.py\n")
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
