"""Generate, validate, build, and normalize the Praxist documentation site."""

from __future__ import annotations

import argparse
import re
import subprocess
from collections.abc import Iterable
from pathlib import Path
from urllib.parse import unquote, urlsplit

import yaml

from praxist.cli import _build_parser

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"
BUILD_DIR = REPO_ROOT / "site"
MKDOCS_CONFIG = REPO_ROOT / "mkdocs.yml"

TEXT_SUFFIXES = {
    ".css",
    ".html",
    ".js",
    ".json",
    ".map",
    ".txt",
    ".xml",
}

MARKDOWN_LINK_RE = re.compile(r"!?\[[^\]]*]\(([^)]+)\)")
FRONT_MATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)


class _MkDocsConfigLoader(yaml.SafeLoader):
    """Read MkDocs callable tags as inert names for source validation."""


def _construct_python_name(
    _loader: yaml.SafeLoader,
    tag_suffix: str,
    _node: yaml.nodes.Node,
) -> str:
    return tag_suffix


_MkDocsConfigLoader.add_multi_constructor(
    "tag:yaml.org,2002:python/name:",
    _construct_python_name,
)


def _escape_table_cell(value: object) -> str:
    """Return one deterministic Markdown table cell."""
    return str(value).replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


def _action_label(action: argparse.Action) -> str:
    """Render an argparse action without duplicating parser semantics."""
    if action.option_strings:
        label = ", ".join(f"`{item}`" for item in action.option_strings)
        if action.metavar:
            label += f" `{action.metavar}`"
        return label
    metavar = action.metavar or action.dest
    return f"`{metavar}`"


def _action_description(action: argparse.Action) -> str:
    """Render choices and defaults next to the parser-owned help text."""
    parts: list[str] = []
    if action.help and action.help != argparse.SUPPRESS:
        parts.append(str(action.help).replace("%(default)s", str(action.default)))
    if action.choices:
        parts.append("Choices: " + ", ".join(f"`{choice}`" for choice in action.choices) + ".")
    if (
        action.default not in (None, False, argparse.SUPPRESS)
        and "%(default)" not in str(action.help or "")
        and not isinstance(action, argparse._HelpAction)
    ):
        parts.append(f"Default: `{action.default}`.")
    return " ".join(parts).strip() or "No additional description."


def _parser_options_table(parser: argparse.ArgumentParser) -> list[str]:
    """Render the non-subcommand actions of one parser."""
    rows = [
        "| Argument | Required | Description |",
        "|---|---:|---|",
    ]
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            continue
        if action.help == argparse.SUPPRESS:
            continue
        required = action.required or (not action.option_strings and action.nargs not in ("?", "*"))
        rows.append(
            "| "
            + " | ".join(
                (
                    _escape_table_cell(_action_label(action)),
                    "yes" if required else "no",
                    _escape_table_cell(_action_description(action)),
                )
            )
            + " |"
        )
    return rows


def _stable_usage(parser: argparse.ArgumentParser) -> str:
    """Render usage at a fixed width independent of the invoking terminal."""

    formatter = argparse.HelpFormatter(parser.prog, width=100)
    formatter.add_usage(parser.usage, parser._actions, parser._mutually_exclusive_groups)
    return formatter.format_help().strip()


def render_cli_reference() -> str:
    """Generate the CLI reference from the live argparse tree."""
    parser = _build_parser()
    subparsers = next(
        action for action in parser._actions if isinstance(action, argparse._SubParsersAction)
    )
    command_help = {
        action.dest: action.help
        for action in subparsers._choices_actions
        if action.dest and action.help != argparse.SUPPRESS
    }
    lines = [
        "<!-- Generated by scripts/build_docs_site.py; do not edit manually. -->",
        "",
        "# CLI Reference",
        "",
        "This page is generated from the same `argparse` tree used by the",
        "`praxist` executable. The command implementation is the sole definition;",
        "rebuild the documentation after changing CLI arguments.",
        "",
        "```text",
        _stable_usage(parser),
        "```",
        "",
        "## Global arguments",
        "",
        *_parser_options_table(parser),
        "",
        "## Commands",
        "",
        "| Command | Purpose |",
        "|---|---|",
    ]
    for name, command_parser in subparsers.choices.items():
        description = command_help.get(name) or command_parser.description or command_parser.prog
        lines.append(
            f"| [`praxist {name}`](#{re.sub(r'[^a-z0-9-]+', '-', f'praxist-{name}'.lower()).strip('-')}) "
            f"| {_escape_table_cell(description)} |"
        )

    for name, command_parser in subparsers.choices.items():
        description = (
            command_parser.description or command_help.get(name) or "No additional description."
        )
        lines.extend(
            [
                "",
                f"## `praxist {name}`",
                "",
                description,
                "",
                "```text",
                _stable_usage(command_parser),
                "```",
                "",
                *_parser_options_table(command_parser),
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def _skill_metadata(path: Path) -> dict[str, str]:
    """Read the public name and description from one skill front matter block."""
    text = path.read_text(encoding="utf-8")
    match = FRONT_MATTER_RE.match(text)
    if not match:
        raise ValueError(f"{path.relative_to(REPO_ROOT)} has no YAML front matter")
    payload = yaml.safe_load(match.group(1))
    if not isinstance(payload, dict):
        raise ValueError(f"{path.relative_to(REPO_ROOT)} has invalid YAML front matter")
    name = str(payload.get("name", "")).strip()
    description = str(payload.get("description", "")).strip()
    if not name or not description:
        raise ValueError(f"{path.relative_to(REPO_ROOT)} must define name and description")
    return {"name": name, "description": description}


def render_skills_reference() -> str:
    """Generate the installed-skill catalog from skill front matter."""
    skills: list[tuple[Path, dict[str, str]]] = []
    for path in sorted((REPO_ROOT / "skills").glob("*/SKILL.md")):
        skills.append((path, _skill_metadata(path)))
    lines = [
        "<!-- Generated by scripts/build_docs_site.py; do not edit manually. -->",
        "",
        "# Skills Reference",
        "",
        "This catalog is generated from bundled `SKILL.md` front matter. Each skill",
        "file is the sole definition of its activation contract and workflow.",
        "Mechanism abbreviations use the compact definitions in the",
        "[Glossary](../about/glossary.md).",
        "",
        "| Skill | Invoke in Codex | Purpose |",
        "|---|---|---|",
    ]
    for path, metadata in skills:
        name = metadata["name"]
        source = path.relative_to(REPO_ROOT).as_posix()
        lines.append(
            f"| `{name}` | `${name}` | {_escape_table_cell(metadata['description'])} "
            f"<br><small>Source: `{source}`</small> |"
        )
    return "\n".join(lines).rstrip() + "\n"


def generated_reference_docs() -> dict[Path, str]:
    """Return every generated source page and its deterministic content."""
    return {
        DOCS_DIR / "reference" / "cli.md": render_cli_reference(),
        DOCS_DIR / "reference" / "skills.md": render_skills_reference(),
    }


def write_generated_reference_docs(*, check: bool = False) -> None:
    """Write generated references or fail when committed copies are stale."""
    stale: list[str] = []
    for path, content in generated_reference_docs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == content:
            continue
        if check:
            stale.append(path.relative_to(REPO_ROOT).as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if stale:
        raise ValueError(
            "generated documentation is stale: "
            + ", ".join(stale)
            + "; run `python scripts/build_docs_site.py`"
        )


def _iter_nav_entries(node: object) -> Iterable[tuple[str, str]]:
    """Yield ``(title, markdown_path)`` pairs in rendered navigation order."""
    if isinstance(node, str):
        yield Path(node).stem.replace("-", " ").title(), node
    elif isinstance(node, list):
        for item in node:
            yield from _iter_nav_entries(item)
    elif isinstance(node, dict):
        for title, value in node.items():
            if isinstance(value, str):
                yield str(title), value
            else:
                yield from _iter_nav_entries(value)


def _load_mkdocs_config() -> dict[str, object]:
    """Load the checked-in MkDocs configuration."""
    payload = yaml.load(
        MKDOCS_CONFIG.read_text(encoding="utf-8"),
        Loader=_MkDocsConfigLoader,
    )
    if not isinstance(payload, dict):
        raise ValueError("mkdocs.yml must contain a mapping")
    return payload


def nav_entries() -> list[tuple[str, str]]:
    """Return the configured documentation navigation."""
    config = _load_mkdocs_config()
    return list(_iter_nav_entries(config.get("nav", [])))


def _link_target(raw: str) -> str:
    """Extract a path from a Markdown link target."""
    target = raw.strip()
    if target.startswith("<") and ">" in target:
        target = target[1 : target.index(">")]
    elif " " in target:
        target = target.split(" ", 1)[0]
    return unquote(urlsplit(target).path)


def validate_docs_sources() -> None:
    """Validate navigation ownership and local Markdown links."""
    entries = nav_entries()
    nav_paths = [path for _, path in entries]
    duplicates = sorted({path for path in nav_paths if nav_paths.count(path) > 1})
    if duplicates:
        raise ValueError(
            "documentation pages appear more than once in nav: " + ", ".join(duplicates)
        )

    missing_nav_targets = sorted(path for path in nav_paths if not (DOCS_DIR / path).is_file())
    if missing_nav_targets:
        raise ValueError("mkdocs nav targets do not exist: " + ", ".join(missing_nav_targets))

    source_pages = sorted(
        path.relative_to(DOCS_DIR).as_posix() for path in DOCS_DIR.rglob("*.md") if path.is_file()
    )
    unowned = sorted(set(source_pages) - set(nav_paths))
    if unowned:
        raise ValueError("documentation pages are not owned by mkdocs nav: " + ", ".join(unowned))

    broken: list[str] = []
    for relative in source_pages:
        source = DOCS_DIR / relative
        for raw_target in MARKDOWN_LINK_RE.findall(source.read_text(encoding="utf-8")):
            target = _link_target(raw_target)
            if not target or raw_target.startswith("#") or urlsplit(raw_target).scheme:
                continue
            if target.startswith("/"):
                continue
            resolved = (source.parent / target).resolve()
            try:
                resolved.relative_to(DOCS_DIR.resolve())
            except ValueError:
                broken.append(f"{relative} -> {raw_target} (outside docs)")
                continue
            if not resolved.exists():
                broken.append(f"{relative} -> {raw_target}")
    if broken:
        raise ValueError("broken local documentation links:\n" + "\n".join(sorted(broken)))


def _strip_front_matter(text: str) -> str:
    """Remove optional YAML front matter from a source page."""
    return FRONT_MATTER_RE.sub("", text, count=1)


def _first_paragraph(text: str) -> str:
    """Extract one compact description for the machine-readable index."""
    paragraphs: list[str] = []
    in_fence = False
    for raw_line in _strip_front_matter(text).splitlines():
        line = raw_line.strip()
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence or not line:
            if paragraphs:
                break
            continue
        line = line.removeprefix("> ").strip()
        if line.startswith(("#", "<!--", "!!!", "???", "|", "-", "*", "1.")):
            continue
        paragraphs.append(line)
    return " ".join(paragraphs).strip()


def generate_llm_exports() -> None:
    """Generate compact and full machine-readable documentation exports."""
    compact = [
        "# Praxist Documentation",
        "",
        "> Versioned documentation for installing, operating, extending, and",
        "> diagnosing the Praxist autonomous research system.",
        "",
    ]
    full = [
        "# Praxist Documentation",
        "",
        "This file is generated from the canonical Markdown pages in navigation order.",
        "",
    ]
    for title, relative in nav_entries():
        source = DOCS_DIR / relative
        text = source.read_text(encoding="utf-8")
        output_path = Path(relative).with_suffix(".html").as_posix()
        description = _first_paragraph(text) or f"Praxist documentation page: {title}."
        compact.append(f"- [{title}]({output_path}): {description}")
        full.extend(
            [
                "---",
                "",
                f"<!-- Source: {relative} -->",
                "",
                _strip_front_matter(text).strip(),
                "",
            ]
        )

    compact_text = "\n".join(compact).rstrip() + "\n"
    full_text = "\n".join(full).rstrip() + "\n"
    for root in (BUILD_DIR, BUILD_DIR / "docs"):
        root.mkdir(parents=True, exist_ok=True)
        (root / "llms.txt").write_text(compact_text, encoding="utf-8")
        (root / "llms-full.txt").write_text(full_text, encoding="utf-8")


def _strip_trailing_whitespace(path: Path) -> None:
    """Normalize generated text assets so git diff checks remain useful."""
    raw = path.read_text(encoding="utf-8")
    lines = [line.rstrip(" \t") for line in raw.splitlines()]
    while lines and lines[-1] == "":
        lines.pop()
    normalized = "\n".join(lines)
    if normalized:
        normalized += "\n"
    if normalized != raw:
        path.write_text(normalized, encoding="utf-8")


def _normalize_generated_site(root: Path) -> None:
    """Normalize only text assets generated by MkDocs."""
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() in TEXT_SUFFIXES:
            _strip_trailing_whitespace(path)


def main() -> None:
    """Generate references, validate docs, and optionally build the static site."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check-generated",
        action="store_true",
        help="Validate generated source pages without rewriting or building the site.",
    )
    args = parser.parse_args()
    write_generated_reference_docs(check=args.check_generated)
    validate_docs_sources()
    if args.check_generated:
        return
    subprocess.run(["mkdocs", "build", "--strict"], cwd=REPO_ROOT, check=True)
    generate_llm_exports()
    _normalize_generated_site(BUILD_DIR)


if __name__ == "__main__":
    main()
