/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BotAnalyticsRouteImport } from './routes/bot-analytics'
import { Route as CallbacksRouteImport } from './routes/callbacks'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FloorRouteImport } from './routes/floor'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as PromisesRouteImport } from './routes/promises'
import { Route as PromptStudioRouteImport } from './routes/prompt-studio'
import { Route as QaRouteImport } from './routes/qa'
import { Route as RedactionRouteImport } from './routes/redaction'
import { Route as RoutingRouteImport } from './routes/routing'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as UpsellRouteImport } from './routes/upsell'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BotAnalyticsRoute = BotAnalyticsRouteImport.update({
  id: '/bot-analytics',
  path: '/bot-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbacksRoute = CallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorRoute = FloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const PromisesRoute = PromisesRouteImport.update({
  id: '/promises',
  path: '/promises',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptStudioRoute = PromptStudioRouteImport.update({
  id: '/prompt-studio',
  path: '/prompt-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactionRoute = RedactionRouteImport.update({
  id: '/redaction',
  path: '/redaction',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/bot-analytics': typeof BotAnalyticsRoute
  '/callbacks': typeof CallbacksRoute
  '/compliance': typeof ComplianceRoute
  '/consent': typeof ConsentRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/disputes': typeof DisputesRoute
  '/documents': typeof DocumentsRoute
  '/floor': typeof FloorRoute
  '/handoff': typeof HandoffRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/promises': typeof PromisesRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/qa': typeof QaRoute
  '/redaction': typeof RedactionRoute
  '/routing': typeof RoutingRoute
  '/sandbox': typeof SandboxRoute
  '/upsell': typeof UpsellRoute
  '/webhooks': typeof WebhooksRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/bot-analytics': typeof BotAnalyticsRoute
  '/callbacks': typeof CallbacksRoute
  '/compliance': typeof ComplianceRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/disputes': typeof DisputesRoute
  '/documents': typeof DocumentsRoute
  '/floor': typeof FloorRoute
  '/handoff': typeof HandoffRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/promises': typeof PromisesRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/qa': typeof QaRoute
  '/redaction': typeof RedactionRoute
  '/routing': typeof RoutingRoute
  '/sandbox': typeof SandboxRoute
  '/upsell': typeof UpsellRoute
  '/webhooks': typeof WebhooksRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/bot-analytics': typeof BotAnalyticsRoute
  '/callbacks': typeof CallbacksRoute
  '/compliance': typeof ComplianceRoute
  '/consent': typeof ConsentRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/disputes': typeof DisputesRoute
  '/documents': typeof DocumentsRoute
  '/floor': typeof FloorRoute
  '/handoff': typeof HandoffRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/promises': typeof PromisesRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/qa': typeof QaRoute
  '/redaction': typeof RedactionRoute
  '/routing': typeof RoutingRoute
  '/sandbox': typeof SandboxRoute
  '/upsell': typeof UpsellRoute
  '/webhooks': typeof WebhooksRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/billing'
    | '/bot-analytics'
    | '/callbacks'
    | '/compliance'
    | '/consent'
    | '/customers'
    | '/dashboard'
    | '/disputes'
    | '/documents'
    | '/floor'
    | '/handoff'
    | '/inbox'
    | '/integrations'
    | '/knowledge-base'
    | '/promises'
    | '/prompt-studio'
    | '/qa'
    | '/redaction'
    | '/routing'
    | '/sandbox'
    | '/upsell'
    | '/webhooks'
    | '/customers/$customerId'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/billing'
    | '/bot-analytics'
    | '/callbacks'
    | '/compliance'
    | '/consent'
    | '/dashboard'
    | '/disputes'
    | '/documents'
    | '/floor'
    | '/handoff'
    | '/inbox'
    | '/integrations'
    | '/knowledge-base'
    | '/promises'
    | '/prompt-studio'
    | '/qa'
    | '/redaction'
    | '/routing'
    | '/sandbox'
    | '/upsell'
    | '/webhooks'
    | '/customers/$customerId'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/billing'
    | '/bot-analytics'
    | '/callbacks'
    | '/compliance'
    | '/consent'
    | '/customers'
    | '/dashboard'
    | '/disputes'
    | '/documents'
    | '/floor'
    | '/handoff'
    | '/inbox'
    | '/integrations'
    | '/knowledge-base'
    | '/promises'
    | '/prompt-studio'
    | '/qa'
    | '/redaction'
    | '/routing'
    | '/sandbox'
    | '/upsell'
    | '/webhooks'
    | '/customers/$customerId'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BillingRoute: typeof BillingRoute
  BotAnalyticsRoute: typeof BotAnalyticsRoute
  CallbacksRoute: typeof CallbacksRoute
  ComplianceRoute: typeof ComplianceRoute
  ConsentRoute: typeof ConsentRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DisputesRoute: typeof DisputesRoute
  DocumentsRoute: typeof DocumentsRoute
  FloorRoute: typeof FloorRoute
  HandoffRoute: typeof HandoffRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  PromisesRoute: typeof PromisesRoute
  PromptStudioRoute: typeof PromptStudioRoute
  QaRoute: typeof QaRoute
  RedactionRoute: typeof RedactionRoute
  RoutingRoute: typeof RoutingRoute
  SandboxRoute: typeof SandboxRoute
  UpsellRoute: typeof UpsellRoute
  WebhooksRoute: typeof WebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-analytics': {
      id: '/bot-analytics'
      path: '/bot-analytics'
      fullPath: '/bot-analytics'
      preLoaderRoute: typeof BotAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callbacks': {
      id: '/callbacks'
      path: '/callbacks'
      fullPath: '/callbacks'
      preLoaderRoute: typeof CallbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor': {
      id: '/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof FloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promises': {
      id: '/promises'
      path: '/promises'
      fullPath: '/promises'
      preLoaderRoute: typeof PromisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-studio': {
      id: '/prompt-studio'
      path: '/prompt-studio'
      fullPath: '/prompt-studio'
      preLoaderRoute: typeof PromptStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redaction': {
      id: '/redaction'
      path: '/redaction'
      fullPath: '/redaction'
      preLoaderRoute: typeof RedactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BillingRoute: BillingRoute,
  BotAnalyticsRoute: BotAnalyticsRoute,
  CallbacksRoute: CallbacksRoute,
  ComplianceRoute: ComplianceRoute,
  ConsentRoute: ConsentRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DisputesRoute: DisputesRoute,
  DocumentsRoute: DocumentsRoute,
  FloorRoute: FloorRoute,
  HandoffRoute: HandoffRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  PromisesRoute: PromisesRoute,
  PromptStudioRoute: PromptStudioRoute,
  QaRoute: QaRoute,
  RedactionRoute: RedactionRoute,
  RoutingRoute: RoutingRoute,
  SandboxRoute: SandboxRoute,
  UpsellRoute: UpsellRoute,
  WebhooksRoute: WebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
