/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAgentStudioRouteImport } from './routes/_app.agent-studio'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppBotAnalyticsRouteImport } from './routes/_app.bot-analytics'
import { Route as AppCallbacksRouteImport } from './routes/_app.callbacks'
import { Route as AppComplianceRouteImport } from './routes/_app.compliance'
import { Route as AppConsentRouteImport } from './routes/_app.consent'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDisputesRouteImport } from './routes/_app.disputes'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppFloorRouteImport } from './routes/_app.floor'
import { Route as AppHandoffRouteImport } from './routes/_app.handoff'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppKnowledgeBaseRouteImport } from './routes/_app.knowledge-base'
import { Route as AppPromisesRouteImport } from './routes/_app.promises'
import { Route as AppQaRouteImport } from './routes/_app.qa'
import { Route as AppRedactionRouteImport } from './routes/_app.redaction'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppRoutingRouteImport } from './routes/_app.routing'
import { Route as AppSandboxRouteImport } from './routes/_app.sandbox'
import { Route as AppTreatmentRouteImport } from './routes/_app.treatment'
import { Route as AppUpsellRouteImport } from './routes/_app.upsell'
import { Route as AppWebhooksRouteImport } from './routes/_app.webhooks'
import { Route as AppAgentStudioIndexRouteImport } from './routes/_app.agent-studio.index'
import { Route as AppAgentStudioBotIdRouteImport } from './routes/_app.agent-studio.$botId'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app.customers.$customerId'
import { Route as AppAgentStudioSkillsIndexRouteImport } from './routes/_app.agent-studio.skills.index'
import { Route as AppAgentStudioSkillsSkillIdRouteImport } from './routes/_app.agent-studio.skills.$skillId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentStudioRoute = AppAgentStudioRouteImport.update({
  id: '/agent-studio',
  path: '/agent-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.audit.lazy').then((d) => d.Route))
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBotAnalyticsRoute = AppBotAnalyticsRouteImport.update({
  id: '/bot-analytics',
  path: '/bot-analytics',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app.bot-analytics.lazy').then((d) => d.Route),
)
const AppCallbacksRoute = AppCallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppConsentRoute = AppConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputesRoute = AppDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppFloorRoute = AppFloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => AppRoute,
} as any)
const AppHandoffRoute = AppHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.handoff.lazy').then((d) => d.Route))
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseRoute = AppKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app.knowledge-base.lazy').then((d) => d.Route),
)
const AppPromisesRoute = AppPromisesRouteImport.update({
  id: '/promises',
  path: '/promises',
  getParentRoute: () => AppRoute,
} as any)
const AppQaRoute = AppQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AppRoute,
} as any)
const AppRedactionRoute = AppRedactionRouteImport.update({
  id: '/redaction',
  path: '/redaction',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutingRoute = AppRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxRoute = AppSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.sandbox.lazy').then((d) => d.Route))
const AppTreatmentRoute = AppTreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app.treatment.lazy').then((d) => d.Route),
)
const AppUpsellRoute = AppUpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentStudioIndexRoute = AppAgentStudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentStudioRoute,
} as any)
const AppAgentStudioBotIdRoute = AppAgentStudioBotIdRouteImport.update({
  id: '/$botId',
  path: '/$botId',
  getParentRoute: () => AppAgentStudioRoute,
} as any).lazy(() =>
  import('./routes/_app.agent-studio.$botId.lazy').then((d) => d.Route),
)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppCustomersRoute,
} as any).lazy(() =>
  import('./routes/_app.customers.$customerId.lazy').then((d) => d.Route),
)
const AppAgentStudioSkillsIndexRoute =
  AppAgentStudioSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => AppAgentStudioRoute,
  } as any)
const AppAgentStudioSkillsSkillIdRoute =
  AppAgentStudioSkillsSkillIdRouteImport.update({
    id: '/skills/$skillId',
    path: '/skills/$skillId',
    getParentRoute: () => AppAgentStudioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/agent-studio': typeof AppAgentStudioRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/bot-analytics': typeof AppBotAnalyticsRoute
  '/callbacks': typeof AppCallbacksRoute
  '/compliance': typeof AppComplianceRoute
  '/consent': typeof AppConsentRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/disputes': typeof AppDisputesRoute
  '/documents': typeof AppDocumentsRoute
  '/floor': typeof AppFloorRoute
  '/handoff': typeof AppHandoffRoute
  '/inbox': typeof AppInboxRoute
  '/integrations': typeof AppIntegrationsRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/promises': typeof AppPromisesRoute
  '/qa': typeof AppQaRoute
  '/redaction': typeof AppRedactionRoute
  '/roles': typeof AppRolesRoute
  '/routing': typeof AppRoutingRoute
  '/sandbox': typeof AppSandboxRoute
  '/treatment': typeof AppTreatmentRoute
  '/upsell': typeof AppUpsellRoute
  '/webhooks': typeof AppWebhooksRoute
  '/agent-studio/$botId': typeof AppAgentStudioBotIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/agent-studio/': typeof AppAgentStudioIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/agent-studio/skills/$skillId': typeof AppAgentStudioSkillsSkillIdRoute
  '/agent-studio/skills/': typeof AppAgentStudioSkillsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/bot-analytics': typeof AppBotAnalyticsRoute
  '/callbacks': typeof AppCallbacksRoute
  '/compliance': typeof AppComplianceRoute
  '/consent': typeof AppConsentRoute
  '/dashboard': typeof AppDashboardRoute
  '/disputes': typeof AppDisputesRoute
  '/documents': typeof AppDocumentsRoute
  '/floor': typeof AppFloorRoute
  '/handoff': typeof AppHandoffRoute
  '/inbox': typeof AppInboxRoute
  '/integrations': typeof AppIntegrationsRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/promises': typeof AppPromisesRoute
  '/qa': typeof AppQaRoute
  '/redaction': typeof AppRedactionRoute
  '/roles': typeof AppRolesRoute
  '/routing': typeof AppRoutingRoute
  '/sandbox': typeof AppSandboxRoute
  '/treatment': typeof AppTreatmentRoute
  '/upsell': typeof AppUpsellRoute
  '/webhooks': typeof AppWebhooksRoute
  '/': typeof AppIndexRoute
  '/agent-studio/$botId': typeof AppAgentStudioBotIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/agent-studio': typeof AppAgentStudioIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/agent-studio/skills/$skillId': typeof AppAgentStudioSkillsSkillIdRoute
  '/agent-studio/skills': typeof AppAgentStudioSkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agent-studio': typeof AppAgentStudioRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/bot-analytics': typeof AppBotAnalyticsRoute
  '/_app/callbacks': typeof AppCallbacksRoute
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/consent': typeof AppConsentRoute
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/disputes': typeof AppDisputesRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/floor': typeof AppFloorRoute
  '/_app/handoff': typeof AppHandoffRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/knowledge-base': typeof AppKnowledgeBaseRoute
  '/_app/promises': typeof AppPromisesRoute
  '/_app/qa': typeof AppQaRoute
  '/_app/redaction': typeof AppRedactionRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/routing': typeof AppRoutingRoute
  '/_app/sandbox': typeof AppSandboxRoute
  '/_app/treatment': typeof AppTreatmentRoute
  '/_app/upsell': typeof AppUpsellRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agent-studio/$botId': typeof AppAgentStudioBotIdRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/agent-studio/': typeof AppAgentStudioIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/agent-studio/skills/$skillId': typeof AppAgentStudioSkillsSkillIdRoute
  '/_app/agent-studio/skills/': typeof AppAgentStudioSkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agent-studio'
    | '/audit'
    | '/billing'
    | '/bot-analytics'
    | '/callbacks'
    | '/compliance'
    | '/consent'
    | '/customers'
    | '/dashboard'
    | '/disputes'
    | '/documents'
    | '/floor'
    | '/handoff'
    | '/inbox'
    | '/integrations'
    | '/knowledge-base'
    | '/promises'
    | '/qa'
    | '/redaction'
    | '/roles'
    | '/routing'
    | '/sandbox'
    | '/treatment'
    | '/upsell'
    | '/webhooks'
    | '/agent-studio/$botId'
    | '/customers/$customerId'
    | '/agent-studio/'
    | '/customers/'
    | '/agent-studio/skills/$skillId'
    | '/agent-studio/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/billing'
    | '/bot-analytics'
    | '/callbacks'
    | '/compliance'
    | '/consent'
    | '/dashboard'
    | '/disputes'
    | '/documents'
    | '/floor'
    | '/handoff'
    | '/inbox'
    | '/integrations'
    | '/knowledge-base'
    | '/promises'
    | '/qa'
    | '/redaction'
    | '/roles'
    | '/routing'
    | '/sandbox'
    | '/treatment'
    | '/upsell'
    | '/webhooks'
    | '/'
    | '/agent-studio/$botId'
    | '/customers/$customerId'
    | '/agent-studio'
    | '/customers'
    | '/agent-studio/skills/$skillId'
    | '/agent-studio/skills'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/agent-studio'
    | '/_app/audit'
    | '/_app/billing'
    | '/_app/bot-analytics'
    | '/_app/callbacks'
    | '/_app/compliance'
    | '/_app/consent'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/disputes'
    | '/_app/documents'
    | '/_app/floor'
    | '/_app/handoff'
    | '/_app/inbox'
    | '/_app/integrations'
    | '/_app/knowledge-base'
    | '/_app/promises'
    | '/_app/qa'
    | '/_app/redaction'
    | '/_app/roles'
    | '/_app/routing'
    | '/_app/sandbox'
    | '/_app/treatment'
    | '/_app/upsell'
    | '/_app/webhooks'
    | '/_app/'
    | '/_app/agent-studio/$botId'
    | '/_app/customers/$customerId'
    | '/_app/agent-studio/'
    | '/_app/customers/'
    | '/_app/agent-studio/skills/$skillId'
    | '/_app/agent-studio/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent-studio': {
      id: '/_app/agent-studio'
      path: '/agent-studio'
      fullPath: '/agent-studio'
      preLoaderRoute: typeof AppAgentStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bot-analytics': {
      id: '/_app/bot-analytics'
      path: '/bot-analytics'
      fullPath: '/bot-analytics'
      preLoaderRoute: typeof AppBotAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/callbacks': {
      id: '/_app/callbacks'
      path: '/callbacks'
      fullPath: '/callbacks'
      preLoaderRoute: typeof AppCallbacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consent': {
      id: '/_app/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AppConsentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disputes': {
      id: '/_app/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AppDisputesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/floor': {
      id: '/_app/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof AppFloorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/handoff': {
      id: '/_app/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof AppHandoffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promises': {
      id: '/_app/promises'
      path: '/promises'
      fullPath: '/promises'
      preLoaderRoute: typeof AppPromisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qa': {
      id: '/_app/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof AppQaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/redaction': {
      id: '/_app/redaction'
      path: '/redaction'
      fullPath: '/redaction'
      preLoaderRoute: typeof AppRedactionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routing': {
      id: '/_app/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AppRoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandbox': {
      id: '/_app/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof AppSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treatment': {
      id: '/_app/treatment'
      path: '/treatment'
      fullPath: '/treatment'
      preLoaderRoute: typeof AppTreatmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upsell': {
      id: '/_app/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof AppUpsellRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent-studio/': {
      id: '/_app/agent-studio/'
      path: '/'
      fullPath: '/agent-studio/'
      preLoaderRoute: typeof AppAgentStudioIndexRouteImport
      parentRoute: typeof AppAgentStudioRoute
    }
    '/_app/agent-studio/$botId': {
      id: '/_app/agent-studio/$botId'
      path: '/$botId'
      fullPath: '/agent-studio/$botId'
      preLoaderRoute: typeof AppAgentStudioBotIdRouteImport
      parentRoute: typeof AppAgentStudioRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/agent-studio/skills/': {
      id: '/_app/agent-studio/skills/'
      path: '/skills'
      fullPath: '/agent-studio/skills/'
      preLoaderRoute: typeof AppAgentStudioSkillsIndexRouteImport
      parentRoute: typeof AppAgentStudioRoute
    }
    '/_app/agent-studio/skills/$skillId': {
      id: '/_app/agent-studio/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/agent-studio/skills/$skillId'
      preLoaderRoute: typeof AppAgentStudioSkillsSkillIdRouteImport
      parentRoute: typeof AppAgentStudioRoute
    }
  }
}

interface AppAgentStudioRouteChildren {
  AppAgentStudioBotIdRoute: typeof AppAgentStudioBotIdRoute
  AppAgentStudioIndexRoute: typeof AppAgentStudioIndexRoute
  AppAgentStudioSkillsSkillIdRoute: typeof AppAgentStudioSkillsSkillIdRoute
  AppAgentStudioSkillsIndexRoute: typeof AppAgentStudioSkillsIndexRoute
}

const AppAgentStudioRouteChildren: AppAgentStudioRouteChildren = {
  AppAgentStudioBotIdRoute: AppAgentStudioBotIdRoute,
  AppAgentStudioIndexRoute: AppAgentStudioIndexRoute,
  AppAgentStudioSkillsSkillIdRoute: AppAgentStudioSkillsSkillIdRoute,
  AppAgentStudioSkillsIndexRoute: AppAgentStudioSkillsIndexRoute,
}

const AppAgentStudioRouteWithChildren = AppAgentStudioRoute._addFileChildren(
  AppAgentStudioRouteChildren,
)

interface AppCustomersRouteChildren {
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppRouteChildren {
  AppAgentStudioRoute: typeof AppAgentStudioRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBotAnalyticsRoute: typeof AppBotAnalyticsRoute
  AppCallbacksRoute: typeof AppCallbacksRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppConsentRoute: typeof AppConsentRoute
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDisputesRoute: typeof AppDisputesRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFloorRoute: typeof AppFloorRoute
  AppHandoffRoute: typeof AppHandoffRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppKnowledgeBaseRoute: typeof AppKnowledgeBaseRoute
  AppPromisesRoute: typeof AppPromisesRoute
  AppQaRoute: typeof AppQaRoute
  AppRedactionRoute: typeof AppRedactionRoute
  AppRolesRoute: typeof AppRolesRoute
  AppRoutingRoute: typeof AppRoutingRoute
  AppSandboxRoute: typeof AppSandboxRoute
  AppTreatmentRoute: typeof AppTreatmentRoute
  AppUpsellRoute: typeof AppUpsellRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentStudioRoute: AppAgentStudioRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppBotAnalyticsRoute: AppBotAnalyticsRoute,
  AppCallbacksRoute: AppCallbacksRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppConsentRoute: AppConsentRoute,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDisputesRoute: AppDisputesRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFloorRoute: AppFloorRoute,
  AppHandoffRoute: AppHandoffRoute,
  AppInboxRoute: AppInboxRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppKnowledgeBaseRoute: AppKnowledgeBaseRoute,
  AppPromisesRoute: AppPromisesRoute,
  AppQaRoute: AppQaRoute,
  AppRedactionRoute: AppRedactionRoute,
  AppRolesRoute: AppRolesRoute,
  AppRoutingRoute: AppRoutingRoute,
  AppSandboxRoute: AppSandboxRoute,
  AppTreatmentRoute: AppTreatmentRoute,
  AppUpsellRoute: AppUpsellRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
